# Generated by Django 3.0.2 on 2020-01-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
