# Generated by Django 3.0.2 on 2020-01-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200127_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='diary_id',
            new_name='diaryId',
        ),
    ]
