# Generated by Django 3.0.2 on 2020-01-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200127_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='diaryId',
            new_name='diary_id',
        ),
        migrations.AlterField(
            model_name='diary',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
