# Generated by Django 3.0.2 on 2020-01-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
