# Generated by Django 3.0.2 on 2020-02-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follower_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='notification',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Notificaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(blank=True, choices=[('Like', 'Like'), ('Comment', 'Comment')], max_length=10, null=True)),
                ('link', models.CharField(max_length=250, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Diary')),
            ],
        ),
    ]
