# Generated by Django 3.0.2 on 2020-02-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200204_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaton',
            new_name='Notification',
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='notification',
            new_name='num_notification',
        ),
    ]
