# Generated by Django 3.0.2 on 2020-02-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200204_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='num_notification',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
