# Generated by Django 3.0.2 on 2020-02-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200204_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='num_notification',
            field=models.BigIntegerField(default=0),
        ),
    ]
